[package]
name = "gltest"
version = "0.1.0"
authors = ["= <minalear@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
gl = "0.14.0"
image = "0.23.11"